### ISSUE TITLE
[BUG] spawn ETXTBSY happening when lambda ends its lifecycle

### ISSUE THREAD

**Issue by karimc1** [alixaxel/chrome-aws-lambda#102]
## Environment
* `chrome-aws-lambda` Version: 2.0.2
* `puppeteer` / `puppeteer-core` Version: 2.0.x
* OS: Unix (AWS lambda)
* Node.js Version: 10

Hi Alixaxel,

This is a new ticket to find a solution concerning the fact that using chrome-aws-lambda is working well when launching a new lambda and we can generate pdf multiple times. From the moment the lambda ends it lifecycle and once the lambda restart we have this error appearing:
 ``` 
{
	"errorType": "Error",
	"errorMessage": "spawn ETXTBSY",
	"trace": [
		"Error: spawn ETXTBSY",
		"    at ChildProcess.spawn (internal/child_process.js:366:11)",
		"    at Object.spawn (child_process.js:551:9)",
		"    at Launcher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:132:40)"
	]
}
```
For information, I use the lambda to provide a service to generate the pdf when receiving a request with a html. The purpose is really to be able to handle multiple calls.

Please find the full code called:

package.json
```
{
  "name": "pdf-generate",
  "version": "7.8.0",
  "description": "Generate a PDF from HTML, then and return it as base 64 and optionnally store it to S3. Useful for insurance certificates.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "EA",
  "private": true,
  "dependencies": {
    "aws-sdk": "^2.305.0",
    "bluebird": "^3.5.1",
    "iltorb": "^2.4.4",
    "lodash": "^4.17.11",
    "minio": "^5.0.0",
    "moment": "^2.22.2"
  }

}
```

index.js
```
const Promise = require('bluebird');
const moment = require('moment');
const AWS = require('aws-sdk');
const constants = require('./messages/constants');
const Minio = require("minio");
const chromium = require('chrome-aws-lambda');


// Usefull when you use external library.
process.env['PATH'] = process.env['PATH'] + ':' + process.env['LAMBDA_TASK_ROOT'];


/**
 *  Convert html to PDF, then  put to S3 and return signed URL
 *
 * @param event is a given object containing html
 *
 * @returns {*}
 */
exports.handler = function (event, context) {

    // Verify that we receive something on the body.
    let body = event;
    console.info("Body object received : ", body);

    // Verify that we getting info on the body, return error if not
    if (isEmptyObject(body) || typeof event.version !== constants.name.UNDEFINED) {
        context.fail(JSON.stringify({
            statusCode: 400,
            body: "Invalid message received."
        }));
    }
    const data = event.data;
    const withSignature = event.withSignature;

    const TODAY = moment().format('YYYYMMDDHHmmss');
    const bucket =  process.env[constants.name.BUCKET_NAME];
    const key = TODAY + '/' +  constants.name.PDF_CERTIFICATE_NAME;

    return convertToPdf(data)
        .then(pdf =>  uploadToS3(pdf, bucket, key))
        .then(() => getURL(bucket, key, constants.name.BUCKET_REGION, withSignature))
        .then( url => {
            const response = {
                "statusCode": 200,
                "url": url
            };
            console.log("response = ", JSON.stringify(response, null, 2));
            context.done(null, response);

        })
        .catch(function (error) {
            // Error on the main method
            context.fail(error);
        });
};


/**
 * Sign URL of object
 * @param bucket
 * @param key
 * @param region
 * @param withSignature
 */
const getURL = function(bucket, key, region, withSignature) {
    if(withSignature) {
        const accessKey = process.env['ACCESS_KEY'];
        const secretKey = process.env['SECRET_KEY'];

        const s3SignConf = {
            endPoint: "s3.amazonaws.com",
            accessKey: accessKey,
            secretKey: secretKey,
            secure: true
        };
        const s3Client = new Minio.Client(s3SignConf);
        return new Promise(function (resolve, reject) {
            const expire = 172800;
            s3Client.presignedGetObject(bucket, key, expire, function (err, res) {
                if (err) reject(err);
                else resolve(res);
            });
        })
            .then(url => {
                return url;
            });
    } else {
        return `https://${bucket}.s3.${region}.amazonaws.com/${key}`;
    }
};

/**
 * Check if object is not empty
 *
 * @param {object}
 * @return boolean true or false
 *
 */
const isEmptyObject = function (object) {
    for (let key in object) {
        if (Object.prototype.hasOwnProperty.call(object, key)) {
            return false;
        }
    }
    return true;
};


/**
 * Convert HTML to PDF, using chrome-aws-lambda
 *
 * @param {string} html - The HTML to convert, in UTF-8
 *
 *
 * @param callback
 */
const convertToPdf = async function (html) {
    console.log("html data: ", html);

    let browser = null;
    try {
        const executablePath = await chromium.executablePath;
        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: executablePath,
            headless: chromium.headless
        });
        const page = await browser.newPage();
        await page.setContent(html);

        const pdf = await page.pdf({
            format: 'A4'
        });

        if (browser !== null) {
            await browser.close()
        }

        return pdf;

    } catch (error) {
        if (browser !== null) {
            await browser.close()
        }
        throw  error;
    }
};



/**
 * Upload a file to S3
 *
 * @param {byte[]} pdf - The file to upload, in base 64
 * @param bucket
 * @param key
 *
 *
 */
const uploadToS3 = function (pdf, bucket, key) {
    console.log(`pdf: ${pdf} , bucket: ${bucket}, key: ${key}`);

    if (!pdf || !bucket || !key) {
        throw new  Error('uploadToS3: missing parameter(s)');
    }

    const  params = {
        Bucket: bucket,
        Key: key,
        Body: Buffer.from(pdf, 'base64')
    };

    const s3 = new AWS.S3();
    return s3.putObject(params).promise();
};



```

 attached and the layer was generated using https://github.com/shelfio/chrome-aws-lambda-layer .

Thanks in advance for your help.

**Comment by alixaxel** [comment]
@karimc1 I'm a bit suspicious of the following snippet:

```js
    let body = event;

    // Verify that we getting info on the body, return error if not
    if (isEmptyObject(body) || typeof event.version !== constants.name.UNDEFINED) {
        context.fail(JSON.stringify({
            statusCode: 400,
            body: "Invalid message received."
        }));
    }

    const data = event.data;
```

You are not breaking out of the rest of the execution flow when you call `context.fail()`.

If that's not the root of issue, could you please share:

1. A sample `event` payload.
2. What `constants.name.UNDEFINED` is supposed to be (is it `undefined`)?

**Comment by karimc1** [comment]
@alixaxel 

Awesome, you definitely solved my problem. Great thanks, I was able to fix the problem by reviewing the part you mentionned by adding a return:

```
let body = event;

    // Verify that we getting info on the body, return error if not
    if (isEmptyObject(body) || typeof event.version !== constants.name.UNDEFINED) {
        context.fail(JSON.stringify({
            statusCode: 400,
            body: "Invalid message received."
        }));
        return;
    }

    const data = event.data;
```

I am closing this ticket.

Bests,
karim
