### ISSUE TITLE
Unable to Run node js script in AWS-Lambda....Code Successfully running locally

### ISSUE THREAD

**Issue by Junaid1111** [alixaxel/chrome-aws-lambda#118]
#50  Environment
 hrome-aws-lambda Version: 2.1.1
puppeteer / puppeteer-core Version: 2.1.1
OS:
Node.js Version: 12.x
Lambda / GCF Runtime: Nodesjs 12.x

## Expected Behavior
Code will Run in aws Lambda

## Current Behavior
2020-04-06 20:21:45.163 Error: Failed to launch the browser process!
/var/task/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/var/task/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/var/task/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:323:22)
    at Interface.close (readline.js:409:8)
    at Socket.onend (readline.js:187:10)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

I got this strange errror...!
Unable to run Code in Lambda

**Comment by alixaxel** [comment]
Seems like you have `puppeteer` in your dependencies, that will not work on AWS Lambda.

You need to use `puppeteer-core` instead.
