### ISSUE TITLE
[BUG] waitForFileChooser leads to timeout in AWS Lambda

### ISSUE THREAD

**Issue by splieth** [alixaxel/chrome-aws-lambda#136]
Im running multiple tests against a portal, one of them being a file upload. That looks something like this:
```js
        // ...
        const [fileChooser] = await Promise.all([
            page.waitForFileChooser(),
            page.click('[data-test=upload-file-dialog-ftw]'),
        ]);
        await fileChooser.accept(['/tmp/some-file']);
```
When I run that on my local machine, everything works fine. Now that I deployed that as AWS Lambda, I get a timeout for the file chooser – any clue what is wrong here?

##  Environment
* `chrome-aws-lambda` Version: 3.0.4
* `puppeteer` / `puppeteer-core` Version: 3.0.4
* OS: Mac
* Node.js Version: 12.8.1
* Lambda / GCF Runtime: `nodejs12.x`

## Expected Behavior
File is uploaded.

## Current Behavior
Timeout from file chooser:
```
TimeoutError: waiting for waiting for file chooser failed: timeout 30000ms exceeded
    at Object.waitWithTimeout (/var/task/node_modules/puppeteer-core/lib/helper.js:153:26)
    at Page.waitForFileChooser (/var/task/node_modules/puppeteer-core/lib/Page.js:148:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all ...
```

## Steps to Reproduce
```js
const chromium = require('chrome-aws-lambda');
const fs = require('fs');

async function handler(event, context, callback) {
    const leFile = '/tmp/some-file';
    const browser = await chromium.puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath,
        headless: chromium.headless,
    });
    const page = await browser.newPage();

    // some page with file upload
    await page.goto("http://localhost:8080/", {
        timeout: 5000,
        waitLoad: true,
        waitUntil: ['networkidle2', 'domcontentloaded'],
    });

    fs.writeFile(leFile, 'foobar', (err) => {
        if (err) console.log(err);
    });
    const [fileChooser] = await Promise.all([
        page.waitForFileChooser(),
        page.click('[data-test=upload-file-dialog]'),
    ]);
    await fileChooser.accept([leFile]);
}
```

**Comment by splieth** [comment]
Never mind, it seems to be a timing problem.
