### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by firnandessicepat** [alixaxel/chrome-aws-lambda#155]
## Environment
* `chrome-aws-lambda` Version: 3.1.1
* `puppeteer-core` Version: 3.1.0
* AWS Lambda`nodejs12.x`
* `pug` Version: 3.0.0

## Expected Behavior
Working

## Current Behavior
Error : 
```
{
  "errorType": "Error",
  "errorMessage": "Could not find browser revision 756035. Run \"npm install\" or \"yarn install\" to download a browser binary.",
  "trace": [
    "Error: Could not find browser revision 756035. Run \"npm install\" or \"yarn install\" to download a browser binary.",
    "    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:59:23)"
  ]
}
```

## Steps to Reproduce
Deploy code into aws-lambda and running the code
```js
const chromium = require('chrome-aws-lambda');
const pug = require('pug');

... omitted basicLambdaCode...

const createPdf = (arraydata) => {
    return new Promise(async (resolve, reject) => {
        try {
            const template = pug.compileFile('./template.pug');
            const html = template({data: arraydata});
            let browser = null;
            try {
                browser = await chromium.puppeteer.launch({
                    args: chromium.args,
                    defaultViewport: chromium.defaultViewport,
                    headless: chromium.headless,
                    executablePath: await chromium.executablePath,
                    timeout: 0
                });
                const page = await browser.newPage();
                const result = await page.setContent(html);
                const pdf = await page.pdf({
                    format: 'A4',
                    printBackground: true,
                    margin: { top: '1cm', right: '1cm', bottom: '1cm', left: '1cm' }
                });
                return resolve(pdf);
            } catch(e){
                return reject(e);
            } finally{
                if(browser != null) {
                    await browser.close();
                }
            }
        } catch(e){
            return reject(e);
        }
    })
}
```
Error Log Details : 
```
START RequestId: b45d9552-44be-46f9-8624-ed6998f084dd Version: $LATEST
2020-07-22T00:43:56.069Z	b45d9552-44be-46f9-8624-ed6998f084dd	ERROR	Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:59:23)
2020-07-22T00:43:56.086Z	b45d9552-44be-46f9-8624-ed6998f084dd	ERROR	Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:59:23)
2020-07-22T00:43:56.086Z	b45d9552-44be-46f9-8624-ed6998f084dd	ERROR	Invoke Error	{"errorType":"Error","errorMessage":"Could not find browser revision 756035. Run \"npm install\" or \"yarn install\" to download a browser binary.","stack":["Error: Could not find browser revision 756035. Run \"npm install\" or \"yarn install\" to download a browser binary.","    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/Launcher.js:59:23)"]}
END RequestId: b45d9552-44be-46f9-8624-ed6998f084dd
REPORT RequestId: b45d9552-44be-46f9-8624-ed6998f084dd	Duration: 996.23 ms	Billed Duration: 1000 ms	Memory Size: 512 MB	Max Memory Used: 121 MB	Init Duration: 885.14 ms
```

Please help Sir thanks.

**Comment by firnandessicepat** [comment]
Sorry my bad, i override some environtment variable
