### ISSUE TITLE
[BUG] Run multiple chrome instances on a single lambda

### ISSUE THREAD

**Issue by WinstonN** [alixaxel/chrome-aws-lambda#161]
Hello, 
I'm trying to run multiple chrome browsers in a single lambda, but I get an error. Can you spot what I could be doing wrong?
This does work with a single instance, and sometimes with 2 executions 

## Environment
* `chrome-aws-lambda` Version: `^5.1.0`
* `puppeteer` / `puppeteer-core` Version: `^5.1.0`
* OS: `Amazon Linux 2 (default lambda nodejs 10.x)`
* Node.js Version: `10.x`
* Lambda / GCF Runtime: `nodejs10.x`

## Code 

```
for (let testExecution = 1; testExecution <= maxTotalTestsPerLambda; testExecution++) {
    try {
      console.log(`test execution ${testExecution} of ${maxTotalTestsPerLambda}`)
      console.log(`test will target ${data['targetUrl']}`)

      // run test
      try {
            browser = await chromium.puppeteer.launch({
              args: chromium.args,
              defaultViewport: chromium.defaultViewport,
              executablePath: await chromium.executablePath,
              headless: chromium.headless,
              ignoreHTTPSErrors: true,
            })
          } catch (error) {
            console.log(error)
      }

    const page = await browser.newPage()

    await page.setUserAgent(userAgent)
    await page.setViewport({ width: 1280, height: 800 })
    await page.goto(targetUrl)
    // ..

    } catch (error) {
      console.log('--- error running the test ---')
      console.log(error)
      return callback(error)
    }

}
```

## Expected Behavior
Multiple browsers will start and the puppeteer script will run

## Current Behavior
Error: spawn ETXTBSY

```
2020-09-03T03:13:52.987Z	02f30362-91da-44d5-8748-ede24a6cfe46	ERROR	Unhandled Promise Rejection	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: spawn ETXTBSY",
    "reason": {
        "errorType": "Error",
        "errorMessage": "spawn ETXTBSY",
        "code": "ETXTBSY",
        "errno": "ETXTBSY",
        "syscall": "spawn",
        "stack": [
            "Error: spawn ETXTBSY",
            "    at ChildProcess.spawn (internal/child_process.js:366:11)",
            "    at Object.spawn (child_process.js:551:9)",
            "    at BrowserRunner.start (/var/task/node_modules/puppeteer-core/lib/cjs/node/BrowserRunner.js:79:34)",
            "    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/cjs/node/Launcher.js:91:16)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: spawn ETXTBSY",
        "    at process.on (/var/runtime/index.js:37:15)",
        "    at process.emit (events.js:198:13)",
        "    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)",
        "    at process._tickCallback (internal/process/next_tick.js:69:34)"
    ]
}
```

## Success and Error logs
```
// sucess
2020-09-03T03:38:22.946Z af8af61b-0505-40de-bbef-051743169489 INFO run::execute
2020-09-03T03:38:22.946Z	af8af61b-0505-40de-bbef-051743169489	INFO	run::execute
2020-09-03T03:38:22.946Z af8af61b-0505-40de-bbef-051743169489 INFO test execution 1 of 2
2020-09-03T03:38:22.946Z af8af61b-0505-40de-bbef-051743169489 INFO test will target https://example.com
2020-09-03T03:38:22.946Z af8af61b-0505-40de-bbef-051743169489 INFO inside run function
2020-09-03T03:38:22.947Z af8af61b-0505-40de-bbef-051743169489 INFO launching chromium - lambda
2020-09-03T03:38:22.947Z af8af61b-0505-40de-bbef-051743169489 INFO test execution 2 of 2
2020-09-03T03:38:22.947Z af8af61b-0505-40de-bbef-051743169489 INFO test will target https://example.com
2020-09-03T03:38:22.947Z af8af61b-0505-40de-bbef-051743169489 INFO inside run function
2020-09-03T03:38:22.947Z af8af61b-0505-40de-bbef-051743169489 INFO launching chromium - lambda
2020-09-03T03:38:27.941Z af8af61b-0505-40de-bbef-051743169489 INFO --- begin ---
2020-09-03T03:38:28.874Z af8af61b-0505-40de-bbef-051743169489 INFO --- begin ---
2020-09-03T03:38:48.339Z af8af61b-0505-40de-bbef-051743169489 INFO --- end ---
2020-09-03T03:38:50.380Z af8af61b-0505-40de-bbef-051743169489 INFO --- end ---
END RequestId: af8af61b-0505-40de-bbef-051743169489
REPORT RequestId: af8af61b-0505-40de-bbef-051743169489 Duration: 27510.99 ms Billed Duration: 27600 ms Memory Size: 3008 MB Max Memory Used: 1058 MB

// failures
START RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc Version: $LATEST
2020-09-03T04:21:43.927Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO run::execute
2020-09-03T04:21:43.930Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test execution 1 of 2
2020-09-03T04:21:43.930Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test will target https://example.com
2020-09-03T04:21:43.931Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO inside run function
2020-09-03T04:21:43.932Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO launching chromium - lambda
2020-09-03T04:21:44.059Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test execution 2 of 2
2020-09-03T04:21:44.059Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test will target https://example.com
2020-09-03T04:21:44.059Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO inside run function
2020-09-03T04:21:44.059Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO launching chromium - lambda
2020-09-03T04:21:44.069Z 5efc889c-4a58-4384-a3ab-08416c5e95bc ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: spawn ETXTBSY","reason":{"errorType":"Error","errorMessage":"spawn ETXTBSY","code":"ETXTBSY","errno":"ETXTBSY","syscall":"spawn","stack":["Error: spawn ETXTBSY"," at ChildProcess.spawn (internal/child_process.js:366:11)"," at
[ERROR] [1599106904072] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
END RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc
REPORT RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc Duration: 269.66 ms Billed Duration: 300 ms Memory Size: 3008 MB Max Memory Used: 117 MB Init Duration: 208.48 ms
RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc Process exited before completing request
START RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc Version: $LATEST
2020-09-03T04:22:37.409Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO run::execute
2020-09-03T04:22:37.413Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test execution 1 of 2
2020-09-03T04:22:37.413Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test will target https://example.com
2020-09-03T04:22:37.413Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO inside run function
2020-09-03T04:22:37.414Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO launching chromium - lambda
2020-09-03T04:22:37.491Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test execution 2 of 2
2020-09-03T04:22:37.491Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO test will target https://example.com
2020-09-03T04:22:37.491Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO inside run function
2020-09-03T04:22:37.491Z 5efc889c-4a58-4384-a3ab-08416c5e95bc INFO launching chromium - lambda
2020-09-03T04:22:37.510Z 5efc889c-4a58-4384-a3ab-08416c5e95bc ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n","reason":{"errorType":"Error","errorMessage":"Failed to launch the browser process!\n\n\nTROUBLE
[ERROR] [1599106957511] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
END RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc
REPORT RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc Duration: 135.36 ms Billed Duration: 200 ms Memory Size: 3008 MB Max Memory Used: 32 MB
RequestId: 5efc889c-4a58-4384-a3ab-08416c5e95bc Process exited before completing request
```

## Steps to Reproduce
See above

**Comment by WinstonN** [comment]
I cannot be the only person hitting this bug WTH

**Comment by alixaxel** [comment]
@WinstonN This is totally expected and not a bug. There's two issues with your approach.

The first is that every time you call `await chromium.executablePath` you're extracting Chromium binary and clearing potential leftover core dump files from previous (still warm) executions. You should call it once outside of the loop and store the resolved path into a variable to only then pass it to `launch()`.

https://github.com/alixaxel/chrome-aws-lambda/blob/f05ef847d3c7b47a2fa41f051b035b2dfa0e7a79/source/index.js#L155-L163

The second issue, is a known limitation of Lambda and there's no way to overcome it (AFAIK).

The Lambda execution model is single-threaded, which means you'll not be able to launch multiple Chromiums on the same Lambda execution. In fact, you're not even able to launch two different browser contexts on the same Chromium instance.

This is also the reason why we need this argument to make it work on Lambda:

https://github.com/alixaxel/chrome-aws-lambda/blob/f05ef847d3c7b47a2fa41f051b035b2dfa0e7a79/source/index.js#L117

The good news is that you're able to overcome this problem altogether by using a fan-out strategy of some kind (RPC, Step Functions, event sourcing, etc) and fire multiple Lambdas to do the same job a single one would do, and more efficiently.

**Comment by andreastepel** [comment]
Although this is closed, I am running into the same issue as I am trying to launch multiple chrome instances on Lambda. Someone found a solution how to do this or is it best practice to launch 4 Lambda functions in parallel?
