### ISSUE TITLE
[BUG] Unhandled Promise Rejection when run on Docker

### ISSUE THREAD

**Issue by nguyensonghao94** [alixaxel/chrome-aws-lambda#173]
chrome-aws-lambda is working very good but when we run on some website we has an error 

" Unhandled Promise Rejection     {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read property 'errorText' of null","reason":{"errorType":"TypeError","errorMessage":"Cannot read property 'errorText' of null","stack":["TypeError: Cannot read property 'errorText' of null","    at Page.<anonymous> (/var/task/index.js:69:40)","    at Page.emit (events.js:315:20)","    at NetworkManager.<anonymous> (/var/task/node_modules/puppeteer-core/lib/Page.js:120:89)","    at NetworkManager.emit (events.js:315:20)","    at NetworkManager._onLoadingFailed (/var/task/node_modules/puppeteer-core/lib/NetworkManager.js:249:14)","    at CDPSession.emit (events.js:315:20)","    at CDPSession._onMessage (/var/task/node_modules/puppeteer-core/lib/Connection.js:166:18)","    at Connection._onMessage (/var/task/node_modules/puppeteer-core/lib/Connection.js:83:25)","    at WebSocket.<anonymous> (/var/task/node_modules/puppeteer-core/lib/WebSocketTransport.js:25:32)","    at WebSocket.onMessage (/var/task/node_modules/ws/lib/event-target.js:132:16)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'errorText' of null","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:315:20)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}"

And when we use puppeteer it still working

**Comment by alixaxel** [comment]
@nguyensonghao94 Can you clarify if you're getting this error on a specific URL?

From your report it's not clear whether this is happening only on Docker or only on a specific URL.

Please share more details, I'll be glad to help.
