### ISSUE TITLE
[BUG] ETXTBSY when launching 

### ISSUE THREAD

**Issue by hamiltonca** [alixaxel/chrome-aws-lambda#187]
## Environment
* `chrome-aws-lambda` Version: 5.5.0
* `puppeteer` / `puppeteer-core` Version: 5.5.0
* OS:  MacOs Catalina 10.15.7
* Node.js Version:  v12.16.3
* Lambda / GCF Runtime:  Node.js 12.x

## Expected Behavior

Simple lambda reads HTML from event.body and returns PDF stream. Intended to be wired up to api-gateway.
With a test event it will just log the binary results.
## Current Behavior

Does not produce PDF and throws error
```
2021-01-15T22:49:17.389Z	c37e163e-a8d2-468a-b3e7-eb8a49172ecf	ERROR	exception caught  Error: spawn ETXTBSY
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:553:9)
    at BrowserRunner.start (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:79:34)
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:84:16)
    at async Runtime.getpdf [as handler] (/var/task/index.js:13:19) {
  errno: 'ETXTBSY',
  code: 'ETXTBSY',
  syscall: 'spawn'
}
```
## Steps to Reproduce

Everything is available here: https://github.com/hamiltonca/html-to-pdf-lambda
```
# Assuming a new clone/install
npm install --only=prod
zip -r <zipFile> . -x '.git*'
<!--
```js
const chromium = require('chrome-aws-lambda')
async function getpdf(event, context) {
    console.log('## ENVIRONMENT VARIABLES: ' + JSON.stringify(process.env))
    console.log('## CONTEXT: ' + JSON.stringify(context))
    console.log('## EVENT: ' + JSON.stringify(event))

    let browser;
    try {
        const reqContent = event.body
        console.log("request content: " + reqContent)
        console.log("launching browser...")
        const executablePath = await chromium.executablePath
        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: executablePath,
            headless: true,
            ignoreHTTPSErrors: true
        });
        console.log("browser launched, setting up page.");
        let page = await browser.newPage();
        await page.setContent(reqContent)
        console.log("page content set... generating pdf")
        const pdf = await page.pdf({
            format: "letter",
            printBackground:true
        })
        const retContent = formatResponse(pdf)
        console.log("retContent: " + JSON.stringify(retContent))
        return retContent

    }
    catch(e) {
        console.error("exception caught ", e)
        return formatError(e)
    }
    finally {
        if (browser) {
            console.log("closing browser")
            await browser.close()
            console.log("browser closed, returning content")
        }
    }
}
function formatResponse(pdf) {
    console.log("formatting response")
    return {
        "statusCode": 200,
        "headers" : {
            "Content-Type": "application/pdf"
        },
        "body" : pdf
    }
}
function formatError(e) {
    console.log("formatting error response")
    return {
        "statusCode" : 500,
        "headers" : {
            "Content-type" : "text/plain"
        },
        "body" : "An error occurred." + e.toString()

    }
}
exports.handler = getpdf
```
-->

## Possible Solution

I think ETXTBSY implies some resource cannot be attained because of an exclusive lock.
Again the entire project for this is at https://github.com/hamiltonca/html-to-pdf-lambda
Hope you can help me with this. Please let me know if you need more info.
Thanks.

**Comment by hamiltonca** [comment]
Is there any possibility I could get some assistance with this? Thanks

**Comment by alixaxel** [comment]
Apologies for only now getting to this @hamiltonca, work has been keeping me busier than usual.

I cannot repro your issue, using your code verbatim (without `event` data) I get the expected output:

```json
{
  "statusCode": 200,
  "headers": {
    "Content-Type": "application/pdf"
  },
  "body": {
    "type": "Buffer",
    "data": [
      37,
      80,
      68,
      ...
      69,
      79,
      70
    ]
  }
}
```

You are right, `ETXTBSY ` signifies that a file is busy.

This usually happens when either:

1. you call `chromium.executablePath` (which inflates the Chromium binary) while puppeteer is using it
2. you don't `await chromium.executablePath`

You seem to be doing everything right and I'm able to successfully run your code, so I would check for lingering references to `chromium.executablePath` - it could be that you are calling it more than once and overlooked it perhaps?
