### ISSUE TITLE
[BUG] Support node 14.x on lambda

### ISSUE THREAD

**Issue by thomaschaaf** [alixaxel/chrome-aws-lambda#193]
## Environment
* `chrome-aws-lambda` Version: 5.5.0
* `puppeteer-core` Version: 5.5.0
* Node.js Version: 14.x
* Lambda Runtime: `nodejs14.x`

## Expected Behavior
Should work :)

## Current Behavior

```
Error: Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by alixaxel** [comment]
@thomaschaaf Version 6.0 published with Node 14.x support, version 7.0 will follow.

**Comment by justin-caldicott** [comment]
I seem to be hitting the same error with node 14.x and 7.0. Fine with 12.x and 7.0. Was this resolved for you @thomaschaaf?

**Comment by timothycarambat** [comment]
@justin-caldicott If you are deploying an AWS lambda instance as well I was just able to resolve this by bundling my own layer and applying that to my AWS lambda instance.
```
 git clone --depth=1 https://github.com/alixaxel/chrome-aws-lambda.git && \
cd chrome-aws-lambda && \
make chrome_aws_lambda.zip
```

then upload `chrome_aws_lambda.zip` as a custom Lambda layer and use that as opposed to the layer maintained by @shelfio

**Comment by bdombro** [comment]
Still doesn't work for me in Lambda 12 and 14 for v6 or v7 😢

**Comment by gseth2021** [comment]
Didn't work for me either. Node 14.17.0, npm 6.14.13, AWS Lambda
Error: Failed to launch chrome!",
        "/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory",

**Comment by charlesanim499** [comment]
Any fixes for this ? Still broken

**Comment by ddennis** [comment]
I had the same issue - but found it was caused by using wrong version of puppeteer-core
This is working for me

```
"dependencies": {
    "@babel/core": "^7.15.0",
    "@babel/preset-env": "^7.8.7",
    "@babel/preset-react": "^7.8.3",
    "@babel/register": "^7.8.6",
    "babel-loader": "^8.0.6",
    "chrome-aws-lambda": "^10.1.0",
    "puppeteer-core": "^10.2.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "regenerator-runtime": "^0.13.9",
    "webpack": "^5.49.0",
    "webpack-cli": "^4.7.2"
  },
  "devDependencies": {
    "puppeteer": "^10.2.0"
  }
```

**Comment by HyperMykola** [comment]
@charlesanim499 , you need to update the lambda layer according to https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer

**Comment by pranavburnwal** [comment]
> @charlesanim499 , you need to update the lambda layer according to [alixaxel/chrome-aws-lambda#aws-lambda-layer](https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer)

Followed exactly this, Still running into the same issue.

here are the logs:
```
Test Event Name
TestEvent

Response
{
  "errorType": "Error",
  "errorMessage": "Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
  "trace": [
    "Error: Failed to launch the browser process!",
    "/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory",
    "",
    "",
    "TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md",
    "",
    "    at onClose (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)",
    "    at Interface.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)",
    "    at Interface.emit (events.js:412:35)",
    "    at Interface.emit (domain.js:475:12)",
    "    at Interface.close (readline.js:530:8)",
    "    at Socket.onend (readline.js:254:10)",
    "    at Socket.emit (events.js:412:35)",
    "    at Socket.emit (domain.js:475:12)",
    "    at endReadableNT (internal/streams/readable.js:1333:12)",
    "    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
  ]
}

Function Logs
2022-10-26T05:24:26.227Z	undefined	INFO	Modules loaded!
2022-10-26T05:24:26.228Z	undefined	INFO	puppeteer
2022-10-26T05:24:26.230Z	undefined	INFO	PuppeteerNode {
  _changedProduct: false,
  _isPuppeteerCore: true,
  _projectRoot: '/opt/nodejs/node_modules/puppeteer-core',
  __productName: undefined,
  _preferredRevision: '884014'
}
2022-10-26T05:24:26.230Z	undefined	INFO	chrome-aws-lambda
2022-10-26T05:24:26.230Z	undefined	INFO	[class Chromium]
START RequestId: d44de733-d165-4bc3-8cff-5c7954f32ae7 Version: $LATEST
2022-10-26T05:24:26.268Z	d44de733-d165-4bc3-8cff-5c7954f32ae7	INFO	chromium.executablePath
2022-10-26T05:24:33.767Z	d44de733-d165-4bc3-8cff-5c7954f32ae7	INFO	/tmp/chromium
2022-10-26T05:24:33.848Z	d44de733-d165-4bc3-8cff-5c7954f32ae7	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n","stack":["Error: Failed to launch the browser process!","/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory","","","TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md","","    at onClose (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)","    at Interface.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)","    at Interface.emit (events.js:412:35)","    at Interface.emit (domain.js:475:12)","    at Interface.close (readline.js:530:8)","    at Socket.onend (readline.js:254:10)","    at Socket.emit (events.js:412:35)","    at Socket.emit (domain.js:475:12)","    at endReadableNT (internal/streams/readable.js:1333:12)","    at processTicksAndRejections (internal/process/task_queues.js:82:21)"]}
END RequestId: d44de733-d165-4bc3-8cff-5c7954f32ae7
REPORT RequestId: d44de733-d165-4bc3-8cff-5c7954f32ae7	Duration: 7618.04 ms	Billed Duration: 7619 ms	Memory Size: 512 MB	Max Memory Used: 397 MB	Init Duration: 793.60 ms

```
