### ISSUE TITLE
[BUG] executablePath should be null in local environment with serverless-offline 6.8.x 

### ISSUE THREAD

**Issue by aldenquimby** [alixaxel/chrome-aws-lambda#194]
## Environment
* `chrome-aws-lambda` Version: 5.5.0
* `puppeteer` / `puppeteer-core` Version: 5.5.0
* OS:  Mac
* Node.js Version:  12.x
* Lambda / GCF Runtime:  nodejs12.x

## Expected Behavior

When using serverless-offline 6.8.x locally, I expect chrome-aws-lambda to launch without errors

## Current Behavior

- Browser fails to launch:
```
Error: Failed to launch the browser process!
/var/folders/cm/z0g60t1x12542bf10mw3sfrm0000gn/T/chromium: /var/folders/cm/z0g60t1x12542bf10mw3sfrm0000gn/T/chromium: cannot execute binary file


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (./node_modules/puppeteer/src/node/BrowserRunner.ts:222:9)
    at ChildProcess.<anonymous> (./node_modules/puppeteer/src/node/BrowserRunner.ts:209:61)
    at ChildProcess.emit (events.js:215:7)
    at ChildProcess.EventEmitter.emit (domain.js:499:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

## Steps to Reproduce
1. Install serverless-offline 6.8.x (this bug does not happen with serverless-offline 5.x)
2. Try to launch browser, eg:
```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

## Possible Solution
- What appears to be happening:
    - `serverless-offline` now fills `process.env.AWS_LAMBDA_FUNCTION_NAME`
    - so `chrome-aws-lambda` thinks `headless=true`
    - so `chrome-aws-lambda` does not have `executablePath=null`
- Here's how I've solved it for now:
```ts
/* eslint-disable import/first */
// Manually tell chrome-aws-lambda if we're running local, before we import it.
if (process.env.IS_OFFLINE === 'true') {
  process.env.IS_LOCAL = 'true';
}

import chromium from 'chrome-aws-lambda';
```
- Recommendation options for real fix:
    - 1. Check for `AWS_EXECUTION_ENV` instead of `AWS_LAMBDA_FUNCTION_NAME` here: https://github.com/alixaxel/chrome-aws-lambda/blob/0dee7fec540341c75652ebd58d3651a2572587f0/source/index.js#L188
    - 2. Check for `IS_OFFLINE` in addition to `IS_LOCAL` here: https://github.com/alixaxel/chrome-aws-lambda/blob/0dee7fec540341c75652ebd58d3651a2572587f0/source/index.js#L183

## Other notes
Here are all relevant `process.env` variables when I boot with serverless-offline 6.8.x:
```
{
  "AWS_ACCESS_KEY_ID": "null",
  "AWS_DEFAULT_REGION": "us-west-2",
  "AWS_LAMBDA_FUNCTION_MEMORY_SIZE": "1024",
  "AWS_LAMBDA_FUNCTION_NAME": "my-app-name",
  "AWS_LAMBDA_FUNCTION_VERSION": "$LATEST",
  "AWS_LAMBDA_LOG_GROUP_NAME": "/aws/lambda/my-app-name",
  "AWS_LAMBDA_LOG_STREAM_NAME": "2016/12/02/[$LATEST]f77ff5e4026c45bda9a9ebcec6bc9cad",
  "AWS_REGION": "us-west-2",
  "AWS_SECRET_ACCESS_KEY": "null",
  "IS_OFFLINE": "true",
  "LAMBDA_RUNTIME_DIR": "/var/runtime",
  "LAMBDA_TASK_ROOT": "/var/task",
  "NODE_ENV": "development",
}
```

**Comment by aldenquimby** [comment]
Thank you @alixaxel !
