### ISSUE TITLE
`socket hang up` on launch within lambda function

### ISSUE THREAD

**Issue by Lane** [alixaxel/chrome-aws-lambda#207]
I'm trying to run this on AWS Lambda 12.x environment with serverless.  Everything is working fine locally, but when I deploy to AWS lambda and run I get `Error: socket hang up` when trying to run `chromium.puppeteer.launch`

## Environment
* `chrome-aws-lambda` Version: 8.0.0
* `puppeteer` / `puppeteer-core` Version: 8.0.0
* OS: Mac
* Node.js Version: 12.x
* Lambda / GCF Runtime: `nodejs12.x`

## Expected Behavior

Puppeteer launches

## Current Behavior

I get a `socket hang up` error:

```
ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://127.0.0.1:33937/devtools/browser/0ba768a2-cfa5-4638-aede-ec8e0334950c',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'socket hang up',
  error: Error: socket hang up
      at connResetException (internal/errors.js:609:14)
      at Socket.socketOnEnd (_http_client.js:458:23)
      at Socket.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'ECONNRESET'
  }
}
```

## Steps to Reproduce

My lambda function is using the following code:

```js
  const chromium = require("chrome-aws-lambda");
  const path = require("path");
  // was getting fontconfig error on lambda without the line below
  process.env.FONTCONFIG_PATH = path.resolve(__dirname, "../");

exports.handler = async (event, context, callback) => {
  const html = "<h1>PDF</h1>";
  let browser = null;
  try {
    // launch browser
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: true,
    });

    console.log("browser launched");

    // create page
    const page = await browser.newPage();
    await page.setContent(html);

    console.log("page content set successfully");

    // create pdf from page
    const pdf = await page.pdf({
      path: "output.pdf",
      format: "Letter",
      printBackground: true,
      scale: 2,
    });
    console.log("created pdf");
    context.success("success");
  } catch (error) {
    console.log(error);
    context.fail("failed");
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }
}
```

## Possible Solution

I saw this issue with the same error: https://github.com/alixaxel/chrome-aws-lambda/issues/96

There is a potential solution there, but I'm not sure how to include those dependencies within an AWS lambda function.

**Comment by alixaxel** [comment]
@Lane How much memory have you allocated to your Lambda function?

**Comment by Lane** [comment]
Hi! I'm at 2048MB

![image](https://user-images.githubusercontent.com/21034/113369964-8338ca00-9317-11eb-974b-59695b106d4c.png)

**Comment by Lane** [comment]
I'm not 100% sure what was going wrong, maybe that the function was not returning anything? or maybe that I wasn't using the callback function?

Anyway, I restructured the code to look like this, and it works.

```js
const chromium = require("chrome-aws-lambda");

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    console.log("browser launched");

    let page = await browser.newPage();

    await page.setContent("<html><body><h1>SamplePDF</h1></body></html>");

    console.log("page content set successfully");

    // create pdf from page
    result = await page.pdf({
      format: "Letter",
      printBackground: true,
      scale: 2,
    });

    console.log("pdf creation successful", result.toString("base64"));
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result.toString("base64"));
};
```

**Comment by Lane** [comment]
quick follow up, this is the line that was what was giving me problems:

```js
process.env.FONTCONFIG_PATH = path.resolve(__dirname, "../../..");
```

had this in because `node-canvas` was giving me issues locally without it. 🤦

**Comment by jpike88** [comment]
this is frustrating, I want to point FONTCONFIG_PATH at a .fonts directory I made as a layer, and have this same block. really frustrating.
