### ISSUE TITLE
[BUG] Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",

### ISSUE THREAD

**Issue by LuisAlberto22** [alixaxel/chrome-aws-lambda#284]
Hi, I followed every step for Aws Lambda, but I get this Bug Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n", 

this is my packet 

`"dependencies": {
    "@sparticuz/chrome-aws-lambda": "^17.1.1",
    "puppeteer-core": "^17.1.3"
  }`

**Comment by lakshyajit165** [comment]
Same issue on AWS Lambda on both node.js versions 12.x and 16.x. Whenever I try to generate a pdf, I get the following in the cloudwatch logs:
```2022-09-22T14:59:27.561Z	be26ba71-a998-4ab1-930a-8aad8ada0fd8	ERROR	Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
Is this an issue with the package itself?

**Comment by lewazo** [comment]
For me it was because the default memory allocated to the lambda was too low. I bumped it to 1024 MB and it works perfectly now.

**Comment by lakshyajit165** [comment]
@lewazo does bumping up the memory carry cost implications as well?

**Comment by lakshyajit165** [comment]
I tried bumping the memory upto 1024 MB. But the issue still persists.

**Comment by LuisAlberto22** [comment]
@lakshyajit165 hi, I've already fix my error, could you upload your code to see the problem?

**Comment by lakshyajit165** [comment]
@LuisAlberto22 sure. Here is my code in the index.js file of a Lambda function. The function is invoked through an API gateway whose content-type in the success case is 'application/pdf' as I intend to return a pdf in the response.
```
const chromium = require('chrome-aws-lambda');

exports.handler = async (event) => {
    // TODO implement
    let browser = null;
    let result = null;
    try {
         browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
        const response = {
            statusCode: 200,
            headers: {'Content-type' : 'application/pdf'},
            body: result.toString('base64'),
            isBase64Encoded : true,
        };
        return response;
    } catch (err) {
        console.error(err);
        const errorResponse = {
            message: "An error occurred while generating PDF. Please try again!" 
        };
        const response = {
            statusCode: 500,
            headers: {'Content-type' : 'application/json'},
            body: JSON.stringify(errorResponse)
        };
        return response;
    } finally {
        if (browser !== null) {
          await browser.close();
        }
    }
    
};
```

**Comment by LuisAlberto22** [comment]
@lakshyajit165 wich node version your lambda is runing? this configuration works for me 
![image](https://user-images.githubusercontent.com/80664920/191798006-8a375d90-787d-4976-b628-c7e513feaca8.png)
my lambda runs with x14
![image](https://user-images.githubusercontent.com/80664920/191798204-028fd381-5db6-4041-a390-3b73794d3251.png)
and my layer too.
![image](https://user-images.githubusercontent.com/80664920/191798309-865bddc7-6f8e-4724-ae28-4c32fc8bd83e.png)

**Comment by lakshyajit165** [comment]
@LuisAlberto22 I was previously using 512 MB of ephemeral storage. I changed it to 1024 and tested, but still facing the same issue. Rest all config like node.js runtime env, memory etc are same :(

**Comment by lakshyajit165** [comment]
And just for your reference. This is what my package.json looks like (which I use to zip and upload to the layer for lambda)
```
{
	"name": "nodejs",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"chrome-aws-lambda": "^10.1.0",
		"puppeteer-core": "^13.1.0"
	}
}
```

**Comment by LuisAlberto22** [comment]
@lakshyajit165 try to install puppeteer-core 10.1.0 or 10.4.0
![image](https://user-images.githubusercontent.com/80664920/191803025-b8b5a83e-f44f-4523-a6f1-75efaa574044.png)
you have the puppeteer version 13.1.0 and chrome-aws-lambda version 10.1.0 the difference between these could be the problem

**Comment by lakshyajit165** [comment]
@LuisAlberto22 same issue with both the versions of puppeteer-core you mentioned. :/

**Comment by LuisAlberto22** [comment]
Can you see how much memory your app is using??

**Comment by lakshyajit165** [comment]
Ok...not sure how/where to check that though...

**Comment by LuisAlberto22** [comment]
you can check it out on your lambda Console https://yourRegion.console.aws.amazon.com/lambda/
then run your function by clicking here
![image](https://user-images.githubusercontent.com/80664920/191807063-7608b249-7ea2-4f63-bc7e-e353db0b8a46.png)

run your lambda, and see your Execution result
![image](https://user-images.githubusercontent.com/80664920/191807296-c868eb63-8a52-46f4-bd7f-97c8f2f098c4.png)

Scroll down and you see the summary with the maxium memory used by the lambda
![image](https://user-images.githubusercontent.com/80664920/191807512-c678f11d-24c9-429b-905c-3a2161a106c7.png)

**Comment by lakshyajit165** [comment]
@LuisAlberto22 This is a snippet from the cloudwatch logs of the time when the request hit.
```
REPORT RequestId: 62da5a5f-498a-43b9-87fb-4d7179def238	Duration: 3169.01 ms	Billed Duration: 3000 ms	Memory Size: 1024 MB	Max Memory Used: 376 MB	Init Duration: 193.29 ms
```
As per this the memory used is 376 MB.

**Comment by LuisAlberto22** [comment]
Ok, this is the last thing I think could work, you have to create a layer [Chrome on layer](https://github.com/shelfio/chrome-aws-lambda-layer), this works with Node.js 16x runtime

**Comment by lakshyajit165** [comment]
@LuisAlberto22 Now it's a different error.
```
ERROR	Error: Cannot find module '/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser'
```
This is happening even if I the bundled puppeteer core dependency is of version 10.1.0 (as you mentioned previously)

**Comment by LuisAlberto22** [comment]
@lakshyajit165 that error is fixed by adding `executablePath: await chromium.executablePath` to the browser config

**Comment by lakshyajit165** [comment]
@LuisAlberto22 that is already added. Just need a clarification, when I added [Chrome on layer](https://github.com/shelfio/chrome-aws-lambda-layer), do I need to change my other layer in which "chrome-aws-lambda" dependency was present or I specifically need "@sparticuz/chrome-aws-lambda" in my package.json as well and bundle it and apply it again?

**Comment by LuisAlberto22** [comment]
no, you don't need to change your layer, just add the new layer that is on the link, change the requiere for const `const chromium = require('@sparticuz/chrome-aws-lambda');
` and change the runtime for x16

**Comment by lakshyajit165** [comment]
Got it. Did all that...still same issue...may be I have to look at a different method to generate the pdf afterall. I only went after puppeteer 'cause it's easy to use. 
Thanks for your swift responses :)

**Comment by saibhargav022** [comment]
@lakshyajit165 I'm also facing the same issue , did you found any resolution or any alternative to generate pdf using aws lambda .?

**Comment by lakshyajit165** [comment]
@saibhargav022 not yet, the only problem is puppeteer is actually a heavy package. And the implementations for that which are supposed to be compatible with lambda don't work so well(based on my findings)

**Comment by saibhargav022** [comment]
@lakshyajit165 can you provide me a snapshot of your aws lambda environment bar

**Comment by lakshyajit165** [comment]
@saibhargav022 sorry but that env is no longer active with me. I brought it down to avoid incurring accidental charges.

**Comment by saibhargav022** [comment]
@lakshyajit165 where should the package.json file is supposed to be , is it inside the environment trajectory or in the node modules trajectory .?

**Comment by JadeMin** [comment]
still ive the same problem atm

**Comment by lbenporat-cloudinary** [comment]
Encountered the same issue intermittently with node v12. Bumping up ephemeral storage for the lambda function resolved the issue for me.

**Comment by krishna3699** [comment]
@lakshyajit165 did you find any solution for this issue.

**Comment by lakshyajit165** [comment]
No. Actually I realized, serverless is kind of useless
