### ISSUE TITLE
[BUG] Does Not Work With Node 16 or 18

### ISSUE THREAD

**Issue by CatfishKrenzer** [alixaxel/chrome-aws-lambda#299]
## Environment
* `chrome-aws-lambda` Version: latest
* `puppeteer` / `puppeteer-core` Version:
* OS:
* Node.js Version: 16.x and 16.x
* Lambda / GCF Runtime: Lambda nodejs16.x / nodejs18.x

## Current Behavior

Not supported in Node 16 or Node 18 

## Error Stack
INFO	Error: Failed to launch the browser process!/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md    

at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)    
at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)    
at Interface.emit (node:events:526:35)    
at Interface.close (node:internal/readline/interface:533:10)    
at Socket.onend (node:internal/readline/interface:259:10)    
at Socket.emit (node:events:526:35)    
at endReadableNT (node:internal/streams/readable:1359:12)    
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) | 
-- | --

**Comment by sumilraweng** [comment]
yes getting same issue

**Comment by veloware** [comment]
https://github.com/alixaxel/chrome-aws-lambda/issues/282

**Comment by fuchengli1024** [comment]
getting same issue

**Comment by 8maxxam8** [comment]
Any update planned?

**Comment by samarth-shah-einfochips** [comment]
I am getting Error: spawn ETXTBSY such error while i am calling url using chromium library. Below is my code where i am getting such error. I have also checked for closing the connection of browser, it is already there in code but i am still getting this error.

const browser = await chromium.puppeteer.launch({
    args: ['--start-maximized', '--ignore-certificate-errors','--no-sandbox'],
    ignoreHTTPSErrors: true,
    headless:true,
    executablePath: await chromium.executablePath,
    defaultViewport
  });

**Comment by talaikis** [comment]
Use `@sparticuz/chromium`

**Comment by samarth-shah-einfochips** [comment]
> @sparticuz/chromium

still getting same error after using @sparticuz/chromium

**Comment by vsateesh86** [comment]
Using this @sparticuz/chromium also getting same error. Could you please let me know any other solution for this.

**Comment by 8maxxam8** [comment]
@vsateesh86 Same on my side!

@talaikis I switched to @sparticuz/chromium, but after launching the browser the rest of the code is not exectuted as expected. The lambda runs into a timeout even though it is set to 60 seconds. When I used "chrome-aws-lambda" the code was working as expected. Any idea what might cause this?

***EDIT***
After updating the lambda node version to 20x the browser is launching as expected. The only issue I currently see is that the loading time is much longer than before. While my setup used to take like 25 seconds, it now takes around 50 seconds without major changes... 

**Which Lambda memory size do you recommend?**

**Comment by sripraveens** [comment]
@8maxxam8 Which version of chrome-aws-lamda and puppeteer core you are using in the node20 runtime?

**Comment by 8maxxam8** [comment]
@sripraveens yes I am using node20 runtime!

**Comment by sripraveens** [comment]
@8maxxam8 Sorry I meant, which version of chrome-aws-lamda and puppeteer core you are using? 

Because I was using the later version in node v14, now since v14 is not supported in lamda, In v20 this is not working for me
