### ISSUE TITLE
[BUG] libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: 

### ISSUE THREAD

**Issue by hkmsadek** [alixaxel/chrome-aws-lambda#305]
Hi there, it was working fine in nodejs 14 but aws lambda now no longer support 14. With version 20.x we get this error 

```

{
    "errorType": "Error",
    "errorMessage": "Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
    "stack": [
        "Error: Failed to launch the browser process!",
        "/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory",
        "",
        "",
        "TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md",
        "",
        "    at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)",
        "    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)",
        "    at Interface.emit (node:events:531:35)",
        "    at Interface.emit (node:domain:488:12)",
        "    at Interface.close (node:internal/readline/interface:528:10)",
        "    at Socket.onend (node:internal/readline/interface:254:10)",
        "    at Socket.emit (node:events:531:35)",
        "    at Socket.emit (node:domain:488:12)",
        "    at endReadableNT (node:internal/streams/readable:1696:12)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"
    ]
}


```

**Comment by aoropeza** [comment]
Getting the same error when upgrade to node 20

**Comment by ffxsam** [comment]
We're desperately trying to solve this issue. Anyone have a workaround or fix yet?

**Comment by dockleryxk** [comment]
@ffxsam any luck?

**Comment by ffxsam** [comment]
@dockleryxk No, unfortunately not. I haven't stumbled across any new fixes or workarounds. Our last resort is to just pay for a service like [Urlbox](https://urlbox.com/). (we wanted to use Playwright for automated screenshots)
