### ISSUE TITLE
Error: Cannot find module 'iltorb' #33 [BUG]

### ISSUE THREAD

**Issue by daolf** [alixaxel/chrome-aws-lambda#50]
When running on aws lambda through layer and using proxy I have this trace:

```
{
    "errorMessage": "Cannot find module 'iltorb'",
    "errorType": "Error",
    "stackTrace": [
        "Error: Cannot find module 'iltorb'",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:591:27)",
        "    at Module.require (internal/modules/cjs/loader.js:723:19)",
        "    at require (internal/modules/cjs/helpers.js:14:16)",
        "    at inflate (/Users/daolf/node_modules/chrome-aws-lambda/source/index.js:200:14)",
        "    at Function.get executablePath [as executablePath] (/Users/daolf/node_modules/chrome-aws-lambda/source/index.js:159:7)",
        "    at module.exports.hello (/Users/daolf/Code/ProjetPerso/scrapingninja/scrapingninja-lambda/lambda-js/handler_puppeteer.js:13:40)",
        "    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:593:30)",
        "    at Promise._execute (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:313:9)",
        "    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:488:18)",
        "    at new Promise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:79:10)",
        "    at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:547:12)",
        "    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:151:19)",
        "    at AwsInvokeLocal.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)",
        "    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31)",
        "    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18)",
        "    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:611:10)",
        "    at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:142:12)",
        "    at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)",
        "    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)",
        "    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)",
        "    at processImmediate (internal/timers.js:443:21)",
        "    at process.topLevelDomainCallback (domain.js:136:23)"
    ]
}
```

I use proxy by adding `--proxy-server=0.0.0.0:3128` to the args.

My version: 1.18.1

**Comment by alixaxel** [comment]
Which Lambda version are you using?

**Comment by daolf** [comment]
Node 8.10

**Comment by daolf** [comment]
Nevermind, I was the problem, was running the lambda on local ...

**Comment by daolf** [comment]
Thank you for your quick answer !
