### ISSUE TITLE
[BUG] node v12

### ISSUE THREAD

**Issue by pavelloz** [alixaxel/chrome-aws-lambda#76]
## Environment
* `chrome-aws-lambda` Version: 2
* `puppeteer` / `puppeteer-core` Version: 2
* Node.js Version: 12
* Lambda / GCF Runtime: Lambda

I tried to upgrade node10 to node12 to not get to almost-EOL like last time: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

## Expected Behavior
It should work.

## Current Behavior

```
INFO	Error! - Failed to launch chrome!
/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
{
    "errorType": "Error",
    "errorMessage": "Failed to launch chrome!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n",
    "stack": [
      "Error: Failed to launch chrome!",
      "/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory",
      "",
      "",
      "TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md",
      "",
      "    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)",
      "    at postError (/var/runtime/CallbackContext.js:30:54)",
      "    at callback (/var/runtime/CallbackContext.js:42:7)",
      "    at /var/runtime/CallbackContext.js:105:16",
      "    at Runtime.e.exports.handler (/var/task/index.js:1:317434)",
      "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
    ]
  }
  
```

## Steps to Reproduce
Upgrade your layer + lambda to use node 12 (from 10), run test event that was working on node 10.

**Comment by alixaxel** [comment]
Thanks for bringing this up to my attention @pavelloz :+1: I'll try to close it during the weekend.

**Comment by alixaxel** [comment]
@pavelloz Version `2.0.1` supporting Node 12 just published. :sunglasses:
