### ISSUE TITLE
[BUG] Failed to launch chrome 

### ISSUE THREAD

**Issue by kevsersrca** [alixaxel/chrome-aws-lambda#82]
## Environment
* `chrome-aws-lambda` :2
* `puppeteer` / `puppeteer-core` :2
*  OS: osx docker lambda working but lambda runtime node12.x not working
* Node.js Version:12
* Lambda / GCF Runtime:Lambda

## Expected Behavior
It should work.

## Current Behavior
Lambda response
```
{
  "errorMessage": "Failed to launch chrome!\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n",
  "errorType": "Error",
  "stackTrace": [
    "",
    "",
    "TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md",
    "",
    "onClose (/var/task/node_modules/puppeteer-core/lib/Launcher.js:348:14)",
    "Interface.helper.addEventListener (/var/task/node_modules/puppeteer-core/lib/Launcher.js:337:50)",
    "emitNone (events.js:111:20)",
    "Interface.emit (events.js:208:7)",
    "Interface.close (readline.js:370:8)",
    "Socket.onend (readline.js:149:10)",
    "emitNone (events.js:111:20)",
    "Socket.emit (events.js:208:7)",
    "endReadableNT (_stream_readable.js:1064:12)",
    "_combinedTickCallback (internal/process/next_tick.js:138:11)"
  ]
}
```
## Steps to Reproduce
1- save to index.js
```
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context) => {
	let result = null;
	let browser = null;

	try {
		browser = await chromium.puppeteer.launch({
			args: chromium.args,
			defaultViewport: chromium.defaultViewport,
			executablePath: await chromium.executablePath,
			headless: chromium.headless,
		});

		let page = await browser.newPage();

		await page.goto(event.url || "https://github.com");

		title = await page.title();
        } catch (error) {
		return context.fail(error);
	} finally {
		if (browser !== null) {
			await browser.close();
		}
	}

	return context.succeed(title)
};
```
2- `npm install puppeteer-core chrome-aws-lambda --save-prod`
3- create zip and deploy lambda with runtime node12.x. occur this error.

Thanks,

**Comment by Throwback74** [comment]
I just ran into this issue as well with the Node 10.x runtime. 

I was actually able to run it perfectly fine using my sandbox environment and deploying with Serverless, but once I moved to the proper DEV environment and had to switch over to a SAM template and deploying through Code Pipeline I started getting this error.  I'm at something of a loss as to what caused it

**Comment by chemalopezp** [comment]
I'm getting exactly the same issue, ust with nodejs10.x runtime (updating to v12 soon ;)
Using serverless to package the function (I confirmed both `chrome-aws-lambda`, 42.5 MB, and `puppeteer-core` where in `node_modules`)

```
const chrome = require('chrome-aws-lambda');
// We add puppeteer-core as a dependency just so it is actually packaged into the lambda
// (peer dependency of chrome-aws-lambda)
const puppeteer = require('puppeteer-core'); // eslint-disable-line no-unused-vars

async function renderGraphImage(htmlString) {
  let imageData = null;
  let browser = null;
  try {
    const browser = await chrome.puppeteer.launch({
      args: chrome.args,
      defaultViewport: { width: 450, height: 400 },
      executablePath: await chrome.executablePath,
      headless: chrome.headless,
    });
    const page = await browser.newPage();
    page.setViewport({ width: 450, height: 400 });
    await page.setContent(htmlString);

    const screenshotSettings = {
      omitBackground: true,
    };
    imageData = await page.screenshot(screenshotSettings);
  } catch (error) {
    logger.error('[GRAPH] Puppeteer failed to take screenshot', error);
    return false;
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }
  return imageData;
}
``

Getting the same error:
```
Error: Failed to launch chrome!
/var/folders/f7/03nxf0sn6y1cf5b0g3m386ch0000gp/T/chromium: /var/folders/f7/03nxf0sn6y1cf5b0g3m386ch0000gp/T/chromium: cannot execute binary file


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/Users/jose/lambdas/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/Users/jose/lambdas/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:215:7)
    at Interface.EventEmitter.emit (domain.js:476:20)
    at Interface.close (readline.js:403:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:215:7)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Thanks in advance @alixaxel!

**Comment by atymic** [comment]
Also getting the same issue. I redeployed a previously working function with no code changes, and it's now failing.

Will investigate further.

**Comment by atymic** [comment]
I've tried downgrading versions to `2.0.0` and `1.2.0` with no luck. Lambda sucks in that the issue is extremely hard to debug 😢 

I'm wondering if there's an issue with the decompression? I'm going to dig around a bit more with my fork to try and figure out what's happening.

@alixaxel let me know if there's any info that could help you :)
BTW, you should sign up for github sponsors! I'd donate but I can't via paypal.

**Comment by atymic** [comment]
Ok, i've run out of ideas. Even the previous version of the function that was deploy ~1 week ago that was previously working doesn't work when I invoke that version.

I'm guessing something changed in the container than AWS runs the lambda in, or in the node build they use? I can't think of anything else.

Unfortunately this means none of our functions in production can run, even on old versions :(

**Comment by kevsersrca** [comment]
```
 docker run --rm -v "$PWD":/var/task lambci/lambda:nodejs8.10 index.handler 
```

I was able to deploy my code to the docker by running this command. But still not working on lambda (runtime node8.10)

**Comment by atymic** [comment]
Oh, interesting. I'll have a go with 10.x and see if it's working.

**Comment by atymic** [comment]
Maybe it's worth trying to recompile chromium inside that docker container 🤔

**Comment by atymic** [comment]
Looking further, it looks like it's not actually compiled in the lambda environment so doubt it would help.

**Comment by kevsersrca** [comment]
I try another versions this repo. But same issue. So I decided to transfer my project in selenium environment.

**Comment by atymic** [comment]
Yea, we're currently down in production so working on testing out google cloud as a quick fix. At least serverless and this package supports both :D

**Comment by devasur** [comment]
I do get this problem intermittently in the TEST environment.  It was linked to using as a layer.  The deployment of the layer was in another service. It was referenced and used in the lambda using a CF variable.

The problem went away after redeploying the layer followed by redeploying the lambda using the layer.

I suspect it could be because of a PRUNE plugin I am using to keep trimming older versions from lambda deployment environment.  Not very scientific.

**Comment by atymic** [comment]
I can reproduce the issue on a fresh project on the first deployment, so it's not that in my case.

**Comment by kevsersrca** [comment]
I dont use lambda layer. All sources contain in node_modules folder. and almost all try older versions. Still not working @devasur

**Comment by chemalopezp** [comment]
It might be worth noting that I am now not facing any issue with the actual lambda, but only when using serverless offline in my local computer.
Not sure if it has been a change in my code or just the lambda function. I see a couple of pull requests solving local issues so probably related.

**Comment by atymic** [comment]
I can confirm that's it's working correctly again now. @kevsersrca maybe worth testing?

Literally nothing change (not even a deploy) so no idea what caused the issues. Would still be good to figure it out in case it happens in the future.

**Comment by exentrich** [comment]
Confirm, same error when run locally

**Comment by Gregjarvez** [comment]
```javascript
  const browser = await puppeteerExtra.launch({
     headless: chromium.headless,
     ignoreHTTPSErrors: true,
    executablePath:
      process.env.NODE_ENV !== 'production'
        ? undefined
        : await chromium.executablePath,
    defaultViewport: chromium.defaultViewport,
    args: chromium.args,
  });
```

I got this to work by only using `await chromium.executablePath` in prod as I know this issue has been resolved in cloud functions. I am not exactly sure why this works and didn't have the time to look into it but it does.

**Comment by alixaxel** [comment]
@kevsersrca Sorry for only following up on this now (I've been travelling).

If this is still an issue to you, could you share some more details? Like RAM allocation and `dumpio`:

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context) => {
	let result = null;
	let browser = null;

	try {
		browser = await chromium.puppeteer.launch({
			args: chromium.args,
			defaultViewport: chromium.defaultViewport,
			executablePath: await chromium.executablePath,
			headless: chromium.headless,
			dumpio: true,
		});

		let page = await browser.newPage();

		await page.goto(event.url || "https://github.com");

		title = await page.title();
        } catch (error) {
		return context.fail(error);
	} finally {
		if (browser !== null) {
			await browser.close();
		}
	}

	return context.succeed(title)
};
```

**Comment by alixaxel** [comment]
@chemalopezp Your problem doesn't seem to be the same as @kevsersrca.

I suggest you read the [local development wiki page](https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development).

**Comment by alixaxel** [comment]
@atymic These intermittent failures are worrisome indeed.

Are you still under Node 10? If so, I suggest you update your Lambdas to Node 12.

Otherwise, it would be good to get your logs as well as the specific Node minor version on when this happens again. My suspicion is this: when AWS first made the Node 10 runtime available the version they provided was `10.15.x`, eventually they upgraded it to Node `10.16.x` (and `10.17.x` meanwhile).

When the `10.15.x` -> `10.16.x` switch took place I removed the bundled `iltorb` package for Node 10 (as Node `10.16.x` ships with Brotli support out of the box) - but it could be that, for some reason, you were served with an outdated `10.15.x` execution environment which caused the Brotli inflation to fail.

Hard to be certain tho... :man_shrugging:

**Comment by alixaxel** [comment]
@Gregjarvez Sorry but I'm a bit lost. You're suggesting a fix for Google Cloud Functions?

Could you elaborate on why the `NODE_ENV === 'production'` condition?

**Comment by whitehorse0** [comment]
> @kevsersrca Sorry for only following up on this now (I've been travelling).
> 
> If this is still an issue to you, could you share some more details? Like RAM allocation and `dumpio`:
> 
> ```js
> const chromium = require('chrome-aws-lambda');
> 
> exports.handler = async (event, context) => {
> 	let result = null;
> 	let browser = null;
> 
> 	try {
> 		browser = await chromium.puppeteer.launch({
> 			args: chromium.args,
> 			defaultViewport: chromium.defaultViewport,
> 			executablePath: await chromium.executablePath,
> 			headless: chromium.headless,
> 			dumpio: true,
> 		});
> 
> 		let page = await browser.newPage();
> 
> 		await page.goto(event.url || "https://github.com");
> 
> 		title = await page.title();
>         } catch (error) {
> 		return context.fail(error);
> 	} finally {
> 		if (browser !== null) {
> 			await browser.close();
> 		}
> 	}
> 
> 	return context.succeed(title)
> };
> ```

Sir @alixaxel , I have a same issue, and I have followed the update that you have shown.
I already used the latest version `"chrome-aws-lambda": "^2.0.1"` , Lambdas Node 12.x & ram allocation `512 MB`


code in this line never passed
`let page = await browser.newPage();`

is there anything i missed?

thank you :-/

**Comment by alixaxel** [comment]
@whitehorse0 The exact same code under v2.0.2 and 512MB of RAM on Node 12 works for me:

![image](https://user-images.githubusercontent.com/262782/71783886-f2285580-2fe4-11ea-97f0-670f0f8349b3.png)

**Comment by alixaxel** [comment]
@atymic I finally got accepted into GitHub Sponsors and it's already active.

Thanks for the suggestion! :+1:

**Comment by whitehorse0** [comment]
> @whitehorse0 The exact same code under v2.0.2 and 512MB of RAM on Node 12 works for me:
> 
> ![image](https://user-images.githubusercontent.com/262782/71783886-f2285580-2fe4-11ea-97f0-670f0f8349b3.png)

Oh yes, it works. :+1: 
I'm sorry, the problem is that I did a lot of processes and working on promises, maybe occur race conditions.

thank you for your effort

**Comment by kevsersrca** [comment]
Hi @alixaxel ,

My problem is solved. Thank you for interesting 👍

**Comment by simsketch** [comment]
I'm getting the same Failed to launch chrome error, so I added your launch options @alixaxel and here is the ouput.

```

19:51:31
START RequestId: 5783331b-e829-4287-9363-829e8046ecff Version: $LATEST

19:51:31
2020-01-08T19:51:31.047Z 5783331b-e829-4287-9363-829e8046ecff INFO generating email report

19:51:31
2020-01-08T19:51:31.048Z 5783331b-e829-4287-9363-829e8046ecff INFO { key1: 'value1', key2: 'value2', key3: 'value3' }

19:51:31
[0108/195131.193438:WARNING:resource_bundle.cc(426)] locale_file_path.empty() for locale

19:51:31
DevTools listening on ws://127.0.0.1:33545/devtools/browser/9ef0bc2a-5424-4e80-93b3-5ec63408f649

19:51:32
[0108/195132.109738:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109788:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109794:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109818:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109836:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109848:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109883:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109888:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109892:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109900:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109910:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109920:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109937:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109942:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109946:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109956:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.109995:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110014:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110658:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110695:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110746:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110779:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110875:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110898:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110910:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110936:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110945:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.110958:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111261:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111296:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111312:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111355:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111368:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111378:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111447:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111454:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111458:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111468:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111478:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111489:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111500:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111514:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111525:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111544:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111549:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111553:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111585:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111596:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111605:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111616:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111626:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.111639:WARNING:resource_bundle.cc(1048)] locale resources are not loaded

19:51:32
[0108/195132.327883:ERROR:font_unique_name_lookup_linux.cc(19)] @font-face src: local() instantiation only available when connected to browser process.

19:51:32
[0108/195132.327920:ERROR:font_unique_name_lookup_linux.cc(19)] @font-face src: local() instantiation only available when connected to browser process.

19:51:32
[0108/195132.808748:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -200

19:51:32
[0108/195132.849524:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://bing.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus

19:51:32
[0108/195132.849613:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://bat.bing.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromest

19:51:33
[0108/195133.508574:INFO:CONSOLE(23)] "[Facebook Pixel] - Invalid PixelID: null.", source: https://connect.facebook.net/en_US/fbevents.js (23)

19:51:33
[0108/195133.526964:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://doubleclick.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chrom

19:51:33
[0108/195133.527199:INFO:CONSOLE(0)] "A cookie associated with a resource at http://sanfordcorporation.112.2o7.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatu

19:51:33
[0108/195133.907613:INFO:CONSOLE(0)] "A cookie associated with a resource at http://pubmatic.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633

19:51:33
[0108/195133.908038:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://simage2.pubmatic.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.

19:51:33
[0108/195133.927538:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://casalemedia.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chrom

19:51:33
[0108/195133.947967:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://advertising.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chrom

19:51:34
[0108/195134.008449:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://3lift.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatu

19:51:34
[0108/195134.009243:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://yahoo.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatu

19:51:34
[0108/195134.024259:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://analytics.yahoo.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.c

19:51:34
[0108/195134.087926:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://bidswitch.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromes

19:51:34
[0108/195134.089032:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://ads.yahoo.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromes

19:51:34
[0108/195134.137518:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://openx.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatu

19:51:34
[0108/195134.474512:INFO:CONSOLE(0)] "A cookie associated with a cross-site resource at http://krxd.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus

19:51:36
2020-01-08T19:51:36.510Z 5783331b-e829-4287-9363-829e8046ecff INFO PAGE LOG: A cookie associated with a resource at http://sanfordcorporation.112.2o7.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see

19:51:36
[0108/195136.510720:INFO:CONSOLE(0)] "A cookie associated with a resource at http://sanfordcorporation.112.2o7.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatu

19:51:37
[0108/195137.053167:INFO:CONSOLE(0)] "A cookie associated with a resource at http://sanfordcorporation.112.2o7.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatu

19:51:37
2020-01-08T19:51:37.067Z 5783331b-e829-4287-9363-829e8046ecff INFO PAGE LOG: A cookie associated with a resource at http://sanfordcorporation.112.2o7.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see

19:51:38
2020-01-08T19:51:38.812Z 5783331b-e829-4287-9363-829e8046ecff INFO https://www.endicia.com/Account/NewReports/

19:51:38
2020-01-08T19:51:38.812Z 5783331b-e829-4287-9363-829e8046ecff INFO https://www.endicia.com/Account/AccountReports/rdPage.aspx?&rdframeid=rdFrameeaa37e33-a602-89f7-da6c-f5ba05ddf463&rdSecureKey=31d5850de5e84652958e82d3364cafae

19:51:39
2020-01-08T19:51:39.270Z 5783331b-e829-4287-9363-829e8046ecff INFO PAGE LOG: A cookie associated with a resource at http://sanfordcorporation.112.2o7.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see

19:51:39
[0108/195139.270511:INFO:CONSOLE(0)] "A cookie associated with a resource at http://sanfordcorporation.112.2o7.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatu

19:51:40
2020-01-08T19:51:40.329Z 5783331b-e829-4287-9363-829e8046ecff INFO PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)

19:51:40
2020-01-08T19:51:40.832Z 5783331b-e829-4287-9363-829e8046ecff INFO https://www.endicia.com/Account/AccountReports/rdPage.aspx?&rdframeid=rdFrame6c36664f-26cb-128b-afcf-36e44fec7e49&rdSecureKey=f125a9f5bba24c8fa4a9fd2da6644699

19:51:41
2020-01-08T19:51:41.292Z 5783331b-e829-4287-9363-829e8046ecff INFO Error: EROFS: read-only file system, open 'buddy-screenshot-before.png' -- ASYNC -- at Page.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:111:15) at /var/task/dist/endicia/index.js:71:32 at Generator.next (<anonymous>) at fulfilled (/var/task/dist/endicia/index.js:5:58) { errno: -30, code: '

19:51:41
2020-01-08T19:51:41.292Z 5783331b-e829-4287-9363-829e8046ecff ERROR Invoke Error {"errorType":"Error","errorMessage":"false","stack":["Error: false"," at _homogeneousError (/var/runtime/CallbackContext.js:13:12)"," at postError (/var/runtime/CallbackContext.js:30:54)"," at done (/var/runtime/CallbackContext.js:57:7)"," at fail (/var/runtime/CallbackContext.js:69:7)"," at /var/runti

19:51:41
END RequestId: 5783331b-e829-4287-9363-829e8046ecff

19:51:41
REPORT RequestId: 5783331b-e829-4287-9363-829e8046ecff Duration: 10262.41 ms Billed Duration: 10300 ms Memory Size: 1024 MB Max Memory Used: 567 MB
```

**Comment by alixaxel** [comment]
@simsketch Saw this snippet on my email from you (seems like you edited meanwhile):

```
[0108/195132.808748:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -200
```

You probably need to add `ignoreHTTPSErrors: true` to your `launch()` options.

**Comment by nandeeshsk** [comment]
I am also facing the same error , please suggest, I am struggling to find the solution
 "Error: Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n"

----- Environment ----
AWS Lambda 
--- package versions ----- 
    "chrome-aws-lambda": "^3.1.1",
    "puppeteer-core": "^3.2.0",
   
node version : v12.16.1

---- code as below -------
const chromium = require('chrome-aws-lambda');



exports.generatePDF = async (event, templateName, fileName, data) => {
    try {
        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
            ignoreHTTPSErrors: true,
            dumpio: true,
        });
        page = await browser.newPage();
        await page.emulateMedia('screen');
        await page.setContent(html);
        const pdf = await page.pdf({
            path: fileName,
            format: 'A4',
            printBackground: true,
        });
    };

**Comment by DevGenesis95** [comment]
I'm getting the same error while running it with .net core 2.1 on was lambda but its working locally on my windows machine

**Comment by naveen-repos** [comment]
{
    "errorType": "Error",
    "errorMessage": "Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n",
    "trace": [
        "Error: Failed to launch the browser process!",
        "",
        "",
        "TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md",
        "",
        "    at onClose (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)",
        "    at Interface.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)",
        "    at Interface.emit (events.js:327:22)",
        "    at Interface.close (readline.js:416:8)",
        "    at Socket.onend (readline.js:194:10)",
        "    at Socket.emit (events.js:327:22)",
        "    at endReadableNT (_stream_readable.js:1221:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
    ]
}


- This issue solved for me by giving 1600 MB memory for lambda and 30 sec time out time.
- It run in the environment of node 10.X and 12.X  
- "chrome-aws-lambda": "^5.2.1",
- "puppeteer-core": "^5.2.1"

**Comment by luizwhite** [comment]
I'm having the same error when deploying to **Vercel**
The URL that has my screenshot gives me the following error in the api function logs:

```
ERROR	Error: Failed to launch the browser process!/tmp/chromium: error while
loading shared libraries: libnss3.so: cannot open shared object file: No such file or
directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)  
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by vtolochk** [comment]
I've been struggling a lot with similar issues but the following tutorial saved my life, I just followed all the steps and it works as expected.

https://dev.to/javiertoscano/create-pdf-documents-with-aws-lambda-s3-with-nodejs-and-puppeteer-3phi

**Comment by anuraags** [comment]
I've noticed there was no final answer to this question and I believe I got the correct solution to this without having to downgrade node, from @vtolochk's link.

I was able to fix the exception by increasing the lambda memory limit to 512 mb and increasing the timeout to 25 seconds. I'm not entirely sure if one or the other is enough.
